name: datagrove_flutter
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'
  flutter: ">=1.17.0"

  # flutter, all platforms
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

  # flutter, all platforms
  badges: ^2.0.3
  printing: ^5.9.1
  cupertino_list_tile: ^0.2.1
  provider: ^6.0.3
  flutter_svg: ^1.1.4
  file_picker: ^4.6.1
  universal_html: ^2.0.8
  flutter_markdown: ^0.6.10+2  
  geolocator: ^9.0.0  
  share_plus: ^4.0.9
  modal_bottom_sheet: ^2.1.0
  flutter_secure_storage: ^5.0.2  
  barcode_widget: ^2.0.2  
  any_link_preview: ^2.0.9
  url_launcher: ^6.1.5
  photo_view: ^0.14.0

  flutter_linkify: ^5.0.2     #was for flutter chat
  visibility_detector: ^0.3.3 #was for flutter chat
  flutter_parsed_text: ^2.2.1 #was for flutter chat

  #flutter web only
  webview_flutter_web: ^0.1.0+4
  pointer_interceptor: ^0.9.3+3

  #flutter, not web
  filesystem_picker: ^3.0.0
  
  # flutter phone only (badger is macos too)
  webview_flutter_plus: ^0.3.0+2
  flutter_app_badger: ^1.4.0
  geocoding: ^2.0.4

  # flutter phone and web
  image_picker: ^0.8.5+3
  speech_to_text: ^5.6.0

  #dart things
  json_annotation: ^4.5.0
  pdf: ^3.8.1
  cbor: ^5.0.1
  convert: ^3.0.2
  markdown: ^6.0.0
  equatable: ^2.0.3
  diffutil_dart: ^3.0.0
  linkify: ^4.1.0

  #windows only

  # not windows
  mobile_scanner: ^2.0.0

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  faker: ^2.0.0
  uuid: ^3.0.6
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  dependency_validator: ^3.0.0
  webview_flutter: ^3.0.4

dependency_overrides:
  markdown: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
